using PackProphet.Data;
using PackProphet.Vision;

namespace PackProphet.Tests;

/// <summary>
/// Asserts things about the fingerprint table that is actually committed, rather than about one
/// built in-process. Every rule the screenshot import relies on is a rule about that file, and the
/// file is generated by a tool nobody runs by hand — so the only place the two can be checked
/// against each other is here.
/// </summary>
public class CommittedArtHashesTests
{
    private static CardIndex Ix => Snapshot.Index();

    /// <summary>
    /// The sets the vendored snapshot knows about, which is the population every exact assertion
    /// below is stated over.
    ///
    /// The table is ALLOWED to be ahead of the snapshot, and since the fingerprint refresh learned
    /// to read the release archive it reliably is. The snapshot is a frozen boot fallback taken on
    /// its own cadence; the refresh runs weekly and picks up each new set within days of release.
    /// So a set in the table and not in the snapshot is the two cadences doing their jobs, and the
    /// entries in it have nothing offline to be checked against — the app learns that set from live
    /// card data, which no test here has.
    ///
    /// Before the seam was closed the two stayed accidentally in step: the refresh downloaded from
    /// the art CDN, the newest set is the one the CDN has not published, so the refresh silently
    /// skipped exactly the sets that would have pulled them apart. Which means these assertions
    /// were never really about the snapshot being a census — they would have failed on the first
    /// refresh that worked.
    /// </summary>
    private static HashSet<string> SnapshotSets =>
        Ix.BySet.Keys.ToHashSet(StringComparer.OrdinalIgnoreCase);

    private static ArtHashEntry[] InSnapshotSets =>
        Table.Entries.Where(e => SnapshotSets.Contains(e.Set)).ToArray();

    private static ArtHashTable? _table;

    private static ArtHashTable Table
    {
        get
        {
            if (_table is not null) return _table;

            var path = Path.Combine(AppContext.BaseDirectory, "card-hashes.txt");
            Assert.True(File.Exists(path), $"the committed fingerprint table is missing: {path}");
            return _table = ArtHashTable.Parse(File.ReadAllText(path));
        }
    }

    [Fact]
    public void EveryCardInTheSnapshotHasAFingerprint()
    {
        // A floor on the snapshot, not a census of the table -- see SnapshotSets. Every card that
        // ships has a fingerprint, and the table may hold sets released since.
        Assert.Equal(Ix.All.Count, InSnapshotSets.Length);

        foreach (var (set, cards) in Ix.BySet)
            Assert.Equal(cards.Count, Table.Covered(set));
    }

    [Fact]
    public void WhatTheTableHoldsBeyondTheSnapshotIsWholeSetsAndNotMany()
    {
        // The check that survives allowing the table to run ahead. "Ahead" has a shape: a handful
        // of sets the snapshot has never heard of. A table where a THIRD of the entries are in
        // unknown sets is not a refresh that worked -- it is a generator that read different card
        // data than the app loads, which is the defect the strict equality above used to catch as
        // a side effect.
        var extra = Table.Entries
            .Where(e => !SnapshotSets.Contains(e.Set))
            .GroupBy(e => e.Set, StringComparer.OrdinalIgnoreCase)
            .ToDictionary(g => g.Key, g => g.Count());

        Assert.True(extra.Count <= 3,
            $"{extra.Count} sets are missing from the snapshot ({string.Join(", ", extra.Keys)}) "
            + "-- the snapshot is badly stale, or the generator read the wrong card data");

        Assert.True(extra.Values.Sum() < Ix.All.Count / 10,
            $"{extra.Values.Sum()} of {Table.Count} fingerprints name a set the snapshot lacks");

        // Whole sets, not stragglers. A set arriving with three fingerprints is art the CDN is
        // still publishing; one arriving with 110 is the archive, and it is the archive that this
        // job now reads. Fifty is comfortably below the smallest real set and far above noise.
        Assert.All(extra, kv => Assert.True(kv.Value >= 50,
            $"{kv.Key} has only {kv.Value} fingerprint(s), which is not a whole set"));
    }

    [Fact]
    public void TheArtworkIndependentlyReproducesTheOwnershipDeduplication()
    {
        // The best evidence there is that both halves of the app are right about the same thing.
        //
        // PocketCard.OwnershipKey claims the artwork filename is a card's identity, and CardIndex
        // counts 3,546 ownable cards among 3,761 entries on the strength of that claim. This test
        // arrives at the same number from the pixels: fingerprint every card's art, count the
        // distinct values, and the reprints collapse onto each other because they are the same
        // picture. Two independent routes, one answer.
        // Over the snapshot's own sets, because that is the population CardIndex counted. Include
        // a set the snapshot has never heard of and the two sides stop describing the same thing.
        var distinct = InSnapshotSets.Select(e => e.Hash).Distinct().Count();

        Assert.Equal(Ix.DistinctOwnableCards, distinct);
        Assert.Equal(3664, distinct);
    }

    [Fact]
    public void EveryFingerprintNamesACardTheAppKnowsAbout()
    {
        // A table entry with no card behind it is dead weight the reader would never look up, and a
        // sign the generator ran against different card data than the app loads.
        //
        // Within the snapshot's sets, where "the app knows about it" is answerable offline. A whole
        // set the snapshot lacks is a different thing and is bounded by the test above.
        var orphans = InSnapshotSets
            .Where(e => !Ix.ByKey.ContainsKey(e.Key))
            .Select(e => e.Key)
            .Take(10)
            .ToArray();

        Assert.Empty(orphans);
    }

    [Fact]
    public void NoFingerprintIsFeatureless()
    {
        // A flat fingerprint sits about equally far from thousands of others. One in the table would
        // be a card whose art failed to decode, quietly poisoning every lookup near it.
        Assert.Empty(Table.Entries.Where(e => e.Hash.IsFeatureless).Select(e => e.Key).Take(10));
    }

    [Fact]
    public void TheThresholdsAreStillDefensibleAgainstTheCommittedTable()
    {
        // The numbers the thresholds were chosen from, re-measured. This is the test that fails when
        // a new set arrives full of art too close to what is already there — at which point the
        // thresholds need revisiting rather than the test relaxing.
        var hashes = Table.Entries.Select(e => e.Hash).Distinct().ToArray();
        var nearest = new int[hashes.Length];

        for (var i = 0; i < hashes.Length; i++)
        {
            var best = ArtHash.Bits;
            for (var j = 0; j < hashes.Length; j++)
            {
                if (i == j) continue;
                var d = hashes[i].DistanceTo(hashes[j]);
                if (d < best) best = d;
            }
            nearest[i] = best;
        }

        Array.Sort(nearest);
        var median = nearest[nearest.Length / 2];
        var withinMargin = nearest.Count(d => d < ArtHashTable.AmbiguityMargin);

        // The match threshold has to stay well under the typical distance to a different card,
        // otherwise it will match cards that are not in the table at all.
        Assert.True(median >= ArtHashTable.MaxDistance + 6,
                    $"median separation {median} is too close to the {ArtHashTable.MaxDistance}-bit threshold");

        // Pairs inside the ambiguity margin are unreadable by design. A handful is the cost of not
        // guessing; a flood would mean the fingerprint has stopped discriminating.
        Assert.True(withinMargin <= hashes.Length / 100,
                    $"{withinMargin} of {hashes.Length} fingerprints have a rival within "
                    + $"{ArtHashTable.AmbiguityMargin} bits");
    }

    [Fact]
    public void TheTableSaysWhenItWasBuilt()
    {
        // The coverage warning quotes this date to the user. A table with no stamp turns that into
        // an unfalsifiable apology.
        Assert.NotNull(Table.Generated);
        Assert.Matches(@"^\d{4}-\d{2}-\d{2}$", Table.Generated);
    }

    [Fact]
    public void TheCommittedTableCoversTheSnapshotCompletely()
    {
        var sets = new SetCatalog(Snapshot.PublishedSets(), Ix.BySet.Keys);
        var coverage = ArtHashCoverage.Of(Table, Ix, sets);

        // Complete against the SNAPSHOT, which is what ships. It will not be complete against live
        // CDN card data the moment a set is released, and that is the case the warning exists for —
        // covered in ScreenshotReadingTests rather than here.
        Assert.Empty(coverage.Missing);
        Assert.Empty(coverage.Partial);
        Assert.Null(coverage.Warning(sets));
    }
}
