using PackProphet.Data;
using PackProphet.Vision;

namespace PackProphet.Tests;

/// <summary>
/// Asserts things about the fingerprint table that is actually committed, rather than about one
/// built in-process. Every rule the screenshot import relies on is a rule about that file, and the
/// file is generated by a tool nobody runs by hand — so the only place the two can be checked
/// against each other is here.
/// </summary>
public class CommittedArtHashesTests
{
    private static CardIndex Ix => Snapshot.Index();

    private static ArtHashTable? _table;

    private static ArtHashTable Table
    {
        get
        {
            if (_table is not null) return _table;

            var path = Path.Combine(AppContext.BaseDirectory, "card-hashes.txt");
            Assert.True(File.Exists(path), $"the committed fingerprint table is missing: {path}");
            return _table = ArtHashTable.Parse(File.ReadAllText(path));
        }
    }

    [Fact]
    public void EveryCardInTheSnapshotHasAFingerprint()
    {
        Assert.Equal(Ix.All.Count, Table.Count);

        foreach (var (set, cards) in Ix.BySet)
            Assert.Equal(cards.Count, Table.Covered(set));
    }

    [Fact]
    public void TheArtworkIndependentlyReproducesTheOwnershipDeduplication()
    {
        // The best evidence there is that both halves of the app are right about the same thing.
        //
        // PocketCard.OwnershipKey claims the artwork filename is a card's identity, and CardIndex
        // counts 3,546 ownable cards among 3,761 entries on the strength of that claim. This test
        // arrives at the same number from the pixels: fingerprint every card's art, count the
        // distinct values, and the reprints collapse onto each other because they are the same
        // picture. Two independent routes, one answer.
        var distinct = Table.Entries.Select(e => e.Hash).Distinct().Count();

        Assert.Equal(Ix.DistinctOwnableCards, distinct);
        Assert.Equal(3546, distinct);
    }

    [Fact]
    public void EveryFingerprintNamesACardTheAppKnowsAbout()
    {
        // A table entry with no card behind it is dead weight the reader would never look up, and a
        // sign the generator ran against different card data than the app loads.
        var orphans = Table.Entries
            .Where(e => !Ix.ByKey.ContainsKey(e.Key))
            .Select(e => e.Key)
            .Take(10)
            .ToArray();

        Assert.Empty(orphans);
    }

    [Fact]
    public void NoFingerprintIsFeatureless()
    {
        // A flat fingerprint sits about equally far from thousands of others. One in the table would
        // be a card whose art failed to decode, quietly poisoning every lookup near it.
        Assert.Empty(Table.Entries.Where(e => e.Hash.IsFeatureless).Select(e => e.Key).Take(10));
    }

    [Fact]
    public void TheThresholdsAreStillDefensibleAgainstTheCommittedTable()
    {
        // The numbers the thresholds were chosen from, re-measured. This is the test that fails when
        // a new set arrives full of art too close to what is already there — at which point the
        // thresholds need revisiting rather than the test relaxing.
        var hashes = Table.Entries.Select(e => e.Hash).Distinct().ToArray();
        var nearest = new int[hashes.Length];

        for (var i = 0; i < hashes.Length; i++)
        {
            var best = ArtHash.Bits;
            for (var j = 0; j < hashes.Length; j++)
            {
                if (i == j) continue;
                var d = hashes[i].DistanceTo(hashes[j]);
                if (d < best) best = d;
            }
            nearest[i] = best;
        }

        Array.Sort(nearest);
        var median = nearest[nearest.Length / 2];
        var withinMargin = nearest.Count(d => d < ArtHashTable.AmbiguityMargin);

        // The match threshold has to stay well under the typical distance to a different card,
        // otherwise it will match cards that are not in the table at all.
        Assert.True(median >= ArtHashTable.MaxDistance + 6,
                    $"median separation {median} is too close to the {ArtHashTable.MaxDistance}-bit threshold");

        // Pairs inside the ambiguity margin are unreadable by design. A handful is the cost of not
        // guessing; a flood would mean the fingerprint has stopped discriminating.
        Assert.True(withinMargin <= hashes.Length / 100,
                    $"{withinMargin} of {hashes.Length} fingerprints have a rival within "
                    + $"{ArtHashTable.AmbiguityMargin} bits");
    }

    [Fact]
    public void TheTableSaysWhenItWasBuilt()
    {
        // The coverage warning quotes this date to the user. A table with no stamp turns that into
        // an unfalsifiable apology.
        Assert.NotNull(Table.Generated);
        Assert.Matches(@"^\d{4}-\d{2}-\d{2}$", Table.Generated);
    }

    [Fact]
    public void TheCommittedTableCoversTheSnapshotCompletely()
    {
        var sets = new SetCatalog(Snapshot.PublishedSets(), Ix.BySet.Keys);
        var coverage = ArtHashCoverage.Of(Table, Ix, sets);

        // Complete against the SNAPSHOT, which is what ships. It will not be complete against live
        // CDN card data the moment a set is released, and that is the case the warning exists for —
        // covered in ScreenshotReadingTests rather than here.
        Assert.Empty(coverage.Missing);
        Assert.Empty(coverage.Partial);
        Assert.Null(coverage.Warning(sets));
    }
}
